 
 #NGH 


all: novowels three_letter_pairs palindrome longest_word begins_and_ends_with_he

novowels: 
	gcc -Wall -o novowels novowels.c
	
three_letter_pairs: 
	gcc -Wall -o three_letter_pairs three_letter_pairs.c

palindrome:
	gcc -Wall -o palindrome palindrome.c
	
longest_word:
	gcc -Wall -o longest_word longest_word.c

begins_and_ends_with_he:
	gcc -Wall -o begins_and_ends_with_he begins_and_ends_with_he.c 

clean:
	rm novowels
	rm three_letter_pairs
	rm palindrome
	rm longest_word
	rm begins_and_ends_with_he